# Generated by Django 5.0 on 2024-07-29 04:39

import django.db.models.deletion
import multiattachment1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('leave_type', models.CharField(max_length=20, null=True)),
                ('leave_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_year_id', models.IntegerField(blank=True, null=True)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('leave_deduction_bucket_id', models.CharField(max_length=50, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_count', models.IntegerField(blank=True)),
                ('back_date', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Approved', 'Approved'), ('Withdraw', 'Withdraw'), ('Rejected', 'Rejected')], default='In Process', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('report_back_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiattachment1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=multiattachment1.models.LeaveAttachment.upload_path)),
                ('leaveapply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_leave_attachments', to='multiattachment1.leaveapply')),
            ],
        ),
    ]
