# Generated by Django 5.0 on 2024-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiattachment1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='apply_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
